petition_online/config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :petitions
  resources :votes, only: [:create]
  

end

petition_online/app/models/petition.rb
class Petition < ActiveRecord::Base
  VOTES_TO_WIN = 100
  ACTIVE_PETITION_DAYS = 30

  validates :title, :text, presence: true
  validate :expired

  belongs_to :user
  has_many :votes

  default_scope { order(:created_at => :desc) }

  def votes_to_win
    votes.count >= VOTES_TO_WIN
  end

  def expired
    created_at < ACTIVE_PETITION_DAYS.days.ago
  end

end

petition_online/app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :first_name, :last_name, presence: true
  
  has_many :petitions
  has_many :votes

  has_secure_password

  def name
    "#{first_name} #{last_name}"
  end
end

petition_online/app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :petition
  belongs_to :user
  # validates :petition_id, uniqueness: { scope: :user_id }
  validates :user_id, uniqueness: { scope: :petition_id }
  validate :no_valid_petition, on: :create
  

private
  def no_valid_petition
    petition = Petition.find(petition_id)
    petition.votes_to_win
  end
end

petition_online/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private 
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to new_session_path if current_user.nil?
  end

helper_method :current_user

end

petition_online/app/controllers/petitions_controller.rb
class PetitionsController < ApplicationController
  
  before_filter :authorize, only: [:new, :create, :edit, :destroy]

  def index
    if params[:my]
      @petitions = current_user.petitions
    else
      @petitions = Petition.all
    end
  end
  
  def new
    @petition = Petition.new
  end

  def create
    @petition = current_user.petitions.create(petition_params)
    if @petition.save
      flash[:notice] = 'Петиция создана'
      redirect_to @petition
    else
      render 'new'
    end
  end

  def show
    @petition = Petition.find(params[:id])
  end

  def edit
    @petition = current_user.petitions.find(params[:id])
    if @petition.expired or @petition.votes_to_win
      redirect_to petition_path
      flash[:error] = 'Вы не можете редактировать эту петицию'
    end
  end

  def update
    petition = current_user.petitions.find(params[:id])
    if petition.update(petition_params)
      flash[:notice] = "Петиция обновлена"
      redirect_to petition
    else
      render 'edit'
    end
  end

  def destroy
    petition = current_user.petitions.find(params[:id])
    petition.destroy
 
    redirect_to action: :index
    flash[:error] = "Петиция удалена"
  end

private 
  def petition_params
    params.require(:petition).permit(:title, :text)
  end
end

petition_online/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = 'Добро пожаловать'
      redirect_to root_url
    else
      flash[:error] = 'Пароль или логин не подходят'
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Вы вышли'
    redirect_to root_url
  end
end

petition_online/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(users_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url
      flash[:notice] = 'Спасибо за регистрацию'
    else
      render 'new'
    end
  end

  def show
    
  end

  private
  def users_params
    params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation)
  end
end

petition_online/app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :authorize

  def create
      vote = current_user.votes.create(vote_params)
      if vote.save 
        flash[:notice] = 'Спасибо за ваш голос!'
        redirect_to vote.petition
      end
  end

private
  def vote_params
    params.permit(:petition_id)
  end
end

petition_online/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @petitions = Petition.first(10)
  end
end

petition_online/app/helpers/application_helper.rb
module ApplicationHelper
end

petition_online/app/helpers/petitions_helper.rb
module PetitionsHelper
end

petition_online/app/helpers/sessions_helper.rb
module SessionsHelper
end

petition_online/app/helpers/users_helper.rb
module UsersHelper
end

petition_online/app/helpers/votes_helper.rb
module VotesHelper
end

petition_online/app/helpers/welcome_helper.rb
module WelcomeHelper
end

petition_online/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Онлайн петиции нашего района</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-default navbar-static-top">
    <div class="container">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Онлайн петиции нашего района</a>
      <div class="pull-right" style="margin: 10px">
        <span >
          <% if current_user %>
            <%= current_user.email %> 
            (<%= link_to 'Выйти', logout_path %>)
          <% else %>
            <%= link_to 'Зарегестрироваться', signup_path %> | <%= link_to 'Войти', login_path %>
          <% end %>
        </span>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-lg-9">
        <%= bootstrap_flash %>

<%= yield %>

      </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list la">
              <li><h4><%= link_to "Все петиции", petitions_path  %></h4></li>
              <li><h4><%= link_to "Создать петицию", new_petition_path  %></h4></li>
              <% if current_user %>
                <li><h4><%= link_to "Мои петиции", petitions_path(my: true)  %></h4></li>
              <% end %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->
      <footer>
        <p>&copy; OnlinePetitions 2016</p>
      </footer>
    </div>
</body>
</html>

petition_online/app/views/petitions/_form.html.erb
<div>
  <% if @petition.errors.any? %>
    <%= pluralize(@petition.errors.count, 'error')%>: 
    <% @petition.errors.full_messages.each do |ms| %>
      <%= ms %>
    <% end %>
  <% end %>
</div>
<div class="form-group">
  <%= form_for @petition do |f| %>
    <div class="form-group">
      <%= f.label 'Название' %><br>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
   
    <div class="form-group">
      <%= f.label 'Описание' %><br>
      <%= f.text_area :text, class: 'form-control', rows: '5' %>
    </div>
    <div class="action">
      <%= submit_tag @petition.new_record? ? 'Cоздать' : 'Сохранить', class: 'btn btn-success' %>  
    </div>
  <% end %>
</div>

petition_online/app/views/petitions/_petition.html.erb
<h2>Петиция</h2>
<h3><%= @petition.title %></h3>
<p><%= @petition.created_at.strftime('%d/%m/%Y %H:%M') %></p> 
<p><%= @petition.text %></p>
<p><strong>Голосов: <%= @petition.votes.count %></strong></p>

petition_online/app/views/petitions/edit.html.erb
<h2>Обновить петицию</h2>
<%= render 'form' %>

petition_online/app/views/petitions/index.html.erb
<h2><%= params[:my] ? 'Мои' : 'Все' %> петиции</h2>
<table class="table">
  <thead>
    <tr>
      <th class="col-md-6">Петиция</th>
      <% unless params[:my] %>
        <th class="col-md-3">Автор</th>
      <% end %>
      <th class="col-md-1 text-center">Голоса</th>
      <th class="col-md-3 text-center">Дата создания</th>
      <% if params[:my] %>
        <th class="col-md-6 text-center" colspan="2">Действия</th>
      <% end %>
    </tr>
  </thead>
  <% @petitions.each do |petition| %>
    <tr>
      <td class="col-md-5"><%= link_to petition.title, petition_path(petition) %></td>
      <% unless params[:my] %>
        <td class="col-md-3"><%= petition.user.name %></td>
      <% end %>
      <td class="col-md-1 text-center"><%= petition.votes.count %></td>
      <td class="col-md-3 text-center"><%= petition.created_at.strftime('%d/%m/%Y %H:%M') %></td>
      <% if params[:my] %>
        <td class="col-md-3 text-center"><%= link_to 'Изменить', edit_petition_path(petition) %></td>
        <td class="col-md-3 text-center"><%= link_to 'Удалить', petition_path(petition), method: :delete, data: { confirm: 'Вы уверены?' } %></</td>
      <% end %>
    </tr>
  <% end %>
</table>

petition_online/app/views/petitions/new.html.erb
<h2>Новая петиция</h2>
<%= render 'form' %>

petition_online/app/views/petitions/show.html.erb
<%= render 'petition' %>

<% if current_user.nil? %>  
  <p class="text-danger">Только зарегестрированные пользователи могут голосовать</p> 
<% elsif @petition.votes.exists?(user_id: current_user.id) %>
  <p class="text-success">Вы уже голосовали за данную петицию</p>
<% elsif @petition.expired %>
  <p class="text-danger">Голосование уже не возможно</p>
<% else %>
  <p><%= button_to 'Поддержать', votes_path({ petition_id: @petition.id }), class: 'btn btn-success' %></p>
<% end %>

petition_online/app/views/petitions/user_petitions.html.erb
<!-- <h2>Мои петиции</h2>
<table class="table">
<thead>
  <tr>
    <th>Название</th>
    <th></th>
  </tr>
</thead>
  <% @petitions.each do |petition| %>
  <tr>
    <td><%= link_to petition.title, petition_path(petition) %></td>    
  </tr>
  <% end %>
</table> -->

petition_online/app/views/users/new.html.erb
<h2>Регистрация</h2>
<div >
<% if @user.errors.any? %>
  <%= pluralize(@user.errors.count, 'error')%>: 
    <% @user.errors.full_messages.each do |ms| %>
      <%= ms %>
    <% end %>
  <% end %>
  </div>
<div class="form-group">
  <%= form_for @user do |u| %>
    <div class="form-group" style="width: 50%">
      <%= u.label 'Email' %><br>
      <%= u.text_field :email, class: 'form-control' %>
    </div>
   
    <div class="form-group" style="width: 50%">
      <%= u.label 'Имя' %><br>
      <%= u.text_field :first_name, class: 'form-control' %>
    </div>

    <div class="form-group" style="width: 50%">
      <%= u.label 'Фамилия' %><br>
      <%= u.text_field :last_name, class: 'form-control' %>
    </div>
    
    <div class="form-group" style="width: 50%">
      <%= u.label 'Пароль' %><br>
      <%= u.password_field :password, class: 'form-control' %>
    </div>

    <div class="form-group" style="width: 50%">
      <%= u.label 'Подтверждение пароля' %><br>
      <%= u.password_field :password_confirmation, class: 'form-control' %>
    </div>
 
    <p><%= u.submit 'Зарегестрироваться', class: 'btn btn-success' %></p>
  <% end %>
</div>

petition_online/app/views/welcome/index.html.erb
<h2>Последние петиции</h2>
<table class="table">
  <thead>
    <tr>
      <th class="col-md-6">Петиция</th>
      <th class="col-md-3">Автор</th>
      <th class="col-md-1 text-center">Голоса</th>
      <th class="col-md-3 text-center">Дата создания</th>
    </tr>
  </thead>
  <% @petitions.each do |petition| %>
    <tr>
      <td class="col-md-5"><%= link_to petition.title, petition_path(petition) %></td>
      <td class="col-md-3"><%= petition.user.name %></td>
      <td class="col-md-1 text-center"><%= petition.votes.count %></td>
      <td class="col-md-3 text-center"><%= petition.created_at.strftime('%d/%m/%Y %H:%M') %></td>
    </tr>
  <% end %>
</table>